### ISSUE TITLE
Null error when trying to retrieve Dynamics365 forms

### ISSUE THREAD

**Issue by ben-umble** [umbraco/Umbraco.Cms.Integrations#197]
Hi,

I'm trying to use the Dynamics365 integration to display forms on my website. I've installed version 1.3.3 and authenticated okay but when I try to add a form I get a null instance error.

# Useful Details

1. Umbraco version: `9.5.4`
2. Umbraco.Cms.Integrations.Crm.Dynamics version: `1.3.3`
3. I've tried all options for the `Modules` setting in the data type with the same result
4. I've tried downgrading to version 1.3.2 and I do not get the error (no forms show but I believe that's more to do with our Dynamics365 dev instance than a plugin problem).

# Error

```
Received an error from the server
An error occurred
Object reference not set to an instance of an object.

Exception Details
System.NullReferenceException, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Object reference not set to an instance of an object.
Stacktrace
at Umbraco.Cms.Integrations.Crm.Dynamics.Services.DynamicsService.GetForms(DynamicsModule module)
   at Umbraco.Cms.Integrations.Crm.Dynamics.Controllers.FormsController.GetForms(String module)
   at lambda_method2510(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

```

# Supporting Screenshots

## Data Type
![image](https://github.com/umbraco/Umbraco.Cms.Integrations/assets/102685581/94e84a2b-69f4-46e6-ae08-7309a30f9ba9)

## Document Type
![image](https://github.com/umbraco/Umbraco.Cms.Integrations/assets/102685581/7468e9c4-cfcb-4a32-bf84-2b643c5a6887)

## Selecting Form
![image](https://github.com/umbraco/Umbraco.Cms.Integrations/assets/102685581/351974fb-58d3-468c-b722-357a7dc17c1a)

## Error
![image](https://github.com/umbraco/Umbraco.Cms.Integrations/assets/102685581/d87e8cf7-cfd7-4582-b531-dbbab3544bbd)

Thanks,

Ben

**Comment by acoumb** [comment]
Hi @ben-umble ,

The issue has been fixed with the latest patch update [1.3.4](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Crm.Dynamics/1.3.4).

Thank you,
Adrian
